### PR TITLE
Add blog to navbar; cross-post from openscapes.org

### PR DESCRIPTION
**Pull request by jules32**
@erinmr had the good idea to post NASA blogs directly on the nasa-openscapes.github.io site (rather than only on openscapes.org). This will help the site look more "alive" since otherwise the About page is really what we update and that's a bit hidden (rethinking/breaking up the About page will be another step).

We'll be able to continue to publish via GitHub Pages / GitHub Actions, and can either cross-post to openscapes.org or have a quarterly summary on openscapes.org, depending on volume/bandwidth :)

Here's a first mock-up, any thoughts/suggestions? 

Some thoughts: 

- the categories are copied directly from the openscapes.org website; we can remove irrelevant ones here (or not)?
- Maybe possible to add "cross-posted at openscapes.org" somewhere prominent, or automate to add to each post?

image

### CODE REVIEW

**Comment by ScienceCat18** [comment]
Looks great! thanks. Maybe we can add Upcoming Events? e.g. AGU FM DAAC workshop and all other relevant presentations/activities? Or was the idea to have recent past events on the "home/welcome" front page? Wondering if it makes sense to also link/display more prominently the Cookbook, Champions, and Mentors sections (in addition to having them at the top). Sorry if this is way off from the feedback you're looking for.

**Comment by jules32** [comment]
This is great Feedback @ScienceCat18 ! Yes on having upcoming events - and a full list of all the workshops you all have taught in the past too. And great idea to display more prominently from the homepage too. We can make these things happen together

**Comment by erinmr** [comment]
+1 @ScienceCat18 - I like the idea of upcoming events. 
@jules32 - this mockup looks great.

**Comment by jules32** [comment]
Merging the most recent 7 blog posts, with next steps itemized here: https://github.com/Openscapes/how_we_work/issues/292#issuecomment-1768959459

I broke Catalina's comments into 2 additional issues we'll tackle this fall!

**Pull request merged**
