### PR TITLE
quarto convert nasa openscapes site

### PR DESCRIPTION
**Pull request by stefaniebutland**
Work In Progress. The quarto version of the site now seems to have all the functionality of the distill site. Some things to be done / figured out

- [ ] fix conflicting files (see below)
  - do later since last step of fix is to merge with main
- [x] add logo Openscapes-NASA back to top of home page
  - Added it back to top of home page using html. Couldn't see how to do it otherwise.
- [x] make theme look better
  - on distill site, the `theme.css` from UCSB MEDS looks nice; in quarto, the fonts and other formatting don't look as good. Still, it looks better than lumen theme on this site
- [ ] add link to Openscapes Home on nav bar? (distill Home link to NASA-Openscapes was redundant). 
- See how UCSB MEDS does it in distill [website](https://ucsb-meds.github.io/) [GitHub](https://github.com/UCSB-MEDS/UCSB-MEDS.github.io/blob/main/_site.yml)
- [x] consider deleting lines that are currently commented out in `_quarto.yml` and `index.Rmd` once we're happy with changes.
- [ ] set up GitHub Actions to publish
  - take notes & screenshots to update [documentation](https://openscapes.github.io/quarto-website-tutorial/first-observations.html#set-up-github-publishing)

### CODE REVIEW

**Comment by stefaniebutland** [comment]
I'll come back later to look at conflicts (noting conflicting files are all from distill version 🤔)

**Comment by jules32** [comment]
Great progress Stef! I've never seen a draft pull request too so this is cool to see

**Comment by stefaniebutland** [comment]
@jules32 I think I'll need to cowork with you to figure out the rest.

**Comment by jules32** [comment]
I've just pulled and will have a deeper look soon - but at first impression I am liking the way the fonts / css looks!

**Pull request merged**
